name: Psalm

on:
  push:
    paths:
      - '**.php'
      - 'psalm*'

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}

      - name: Run composer install
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_4_LICENSE_KEY }}"
          composer install -n --prefer-dist

      - name: Run Psalm
        run: ./vendor/bin/psalm --shepherd
